import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Footer from '@/Components/Footer'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
    <Head>
        <title>Login - Instagram</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <link rel="icon" href="./Instagram_icon.ico" />
      </Head>
 <main className={styles.main}>                       
      
 <div id="container">
        <section>
            <div class="main-top">
                <div class="logo">
                    <img src="Instagram-logo.png" />
                </div>
                <div>
                    <input type="text" placeholder="username" class="username" />
                    <div>
                        <input type="password" placeholder="password" class="password" />
                    </div>
                    <input type="button" value="Log in" class="login-btn" />
                </div>

                <span class="or"> OR </span>

                <div class="main-bottom">
                    <a href="" class="logInFB"><img class="fa-brands fa-facebook-f" src="Facebook.jpeg"></img> Log in with Facebook </a> <br></br>
                    <a href="" class="forget"> Forgot password </a>
                </div>

            </div>
            <div class="bottom">
                <div class="signUp">
                    Don't have an account? <a href="#">Sign up</a>
                </div>
            </div>
        </section>

        <Footer></Footer>
    </div>
</main>
  </>
  )
  }
